[package]
name = "cosmos-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmrs = { version = "0.13.0", features = ["bip32", "cosmwasm"]}
env_logger = "0.10.0"
prost = { version= "0.11.9" }
rand_core = "0.6.4"
tendermint-rpc = {version="0.31.1", features=["http-client"]}
cosmos-sdk-proto = "0.18.0"
prost-types = "0.11.9"
base64 = "0.21.0"
serde_json = "1.0.96"
serde = { version="1.0.162", features=["serde_derive"]}
thiserror = "1.0.40"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
